### PR TITLE
Allow schema wrapped by lazy to carry ref instead of lazy itself

### PR DESCRIPTION
**Pull request by rattrayalex**
When doing `foo: z.lazy(() => User)`, where `const User = z.object({}).openapi({ref: 'User'})`, I was getting an error that it didn't recognize typeName: ZodLazy.  This fixed that. 

Leaving the code as I have it here should allow you to do `z.lazy(() => User).openapi({ref: 'User'})`, but I'm not sure if that's desirable/needed; if not, the part before the `??` could be removed.

Thanks for making this library!

### CODE REVIEW

**Comment by rattrayalex** [comment]
Ah, not sure this works without further fiddling – I'm later getting this error:

```
Error: Schema "Post" is already registered
    at eval (webpack-internal:///(api)/../node_modules/.pnpm/zod-openapi@2.3.0_zod@3.21.4/node_modules/zod-openapi/lib-commonjs/create/components.js:193:17)
    at Array.reduce (<anonymous>)
    at createSchemaComponents (webpack-internal:///(api)/../node_modules/.pnpm/zod-openapi@2.3.0_zod@3.21.4/node_modules/zod-openapi/lib-commonjs/create/components.js:185:58)
    at createComponents (webpack-internal:///(api)/../node_modules/.pnpm/zod-openapi@2.3.0_zod@3.21.4/node_modules/zod-openapi/lib-commonjs/create/components.js:142:27)
    at createDocument (webpack-internal:///(api)/../node_modules/.pnpm/zod-openapi@2.3.0_zod@3.21.4/node_modules/zod-openapi/lib-commonjs/create/document.js:11:65)
```

which I'm not certain is related, but I think the Post it was trying to re-register was a zodLazy with schema `{$ref: '#/components/schemas/Post'}`, which feels suspicous…

**Comment by samchungy** [comment]
Ooo let me sit on this one, I'll get back to you.

**Comment by samchungy** [comment]
Would that make sense?

https://github.com/colinhacks/zod#json-type

In particular with this one, it would be difficult to determine which type to use a reference from?

**Comment by samchungy** [comment]
Okay I like the idea now, let me work at it

**Comment by jedwards1211** [comment]
In other words it ought to support this too, where you have lazy -> array -> object:

```ts
const BasePost = z.object({
  id: z.string(),
  userId: z.string(),
});

type Post = z.infer<typeof BasePost> & {
  user?: User;
};

const BaseUser = z.object({
  id: z.string(),
});

type User = z.infer<typeof BaseUser> & {
  posts?: Post[];
};

const Post: ZodType<Post> = BasePost.extend({
  user: z.lazy(() => User).optional(),
});

const User: ZodType<User> = BaseUser.extend({
  posts: z.lazy(() => z.array(Post)).optional(), // <= here's the lazy -> array -> object
});

createDocument({
  components: {
    schemas: {
      User,
      Post,
    },
  },
});
```

The output components would roughly look like:
```
{
  components: {
    schemas: {
      User: {
        type: "object",
        properties: {
          id: { type: "string" },
          posts: {
            type: "array",
            items: { $ref: "#/components/schemas/Post" },
          }
        }
      },
      Post: {
        type: "object",
        properties: {
          id: { type: "string" },
          userId: { type: "string" },
          user: { $ref: "#/components/schemas/User" },
        },
      },
    }
  }
}

```

**Comment by jedwards1211** [comment]
And or course we don't want
```
createDocument({
  components: {
    schemas: {
      User,
      Post,
    },
  },
});
```
To end up generating
```
{
  components: {
    schemas: {
      User: { $ref: "#/components/schemas/User" },
      Post: { $ref: "#/components/schemas/Post" },
    }
  }
}
```
So `getDefaultComponents` or `createComponents` ought to call `createSchema(User)` instead of `createSchemaOrRef(User)`, so that it starts generating `User: { type: "object", properties: { ... } }`.  Then when it gets to `z.array(Post)`, it calls `items: createSchemaOrRef(zodArray._def.type, state)`, which returns `{ $ref: "#/components/schemas/Post" }`

**Comment by samchungy** [comment]
I think I've solved it @jedwards1211

**Comment by samchungy** [comment]
Hey @rattrayalex if you want to try it out - [v2.4.0-beta.1](https://github.com/samchungy/zod-openapi/releases/tag/v2.4.0-beta.1) should work for now. Just gonna get https://github.com/samchungy/zod-openapi/pull/103 through before I do a proper release

**Comment by samchungy** [comment]
I've done a release for 2.4.0 just to fix another issue. This should fix your issue, I'll release the optimisation change PR in a separate release 😄

**Comment by rattrayalex** [comment]
Amazing, thanks for the quick turnaround Sam! Excited to keep trying this library!

**Pull request closed without merging**
